config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  ##############################################################################
  ## ROOT LOCATION ##
  ###################
  root "dashboard#index"
  
  ##############################################################################
  ## DEVISE ROUTES ##
  ###################
  devise_for :hr_staffs,          path: 'hr_staffs',          controllers: { sessions: 'hr_staffs/sessions', registrations: 'hr_staffs/registrations' }
  devise_for :maintenance_staffs, path: 'maintenance_staffs', controllers: { sessions: 'maintenance_staffs/sessions' }
  devise_for :management_staffs,  path: 'management_staffs',  controllers: { sessions: 'management_staffs/sessions' }
  
  get 'new_user_session' => 'sessions#new', as: :new_user_session
  
  ##############################################################################
  ## MAIN ROUTES ##
  #################
  resources :maintenance_staffs
  resources :management_staffs
  resources :employee_records
  resources :reports
  
  ##############################################################################
  ## Custom ROUTES ##
  ###################
  resources :equipment_inventories do
    member do
      post :toggle_status
    end
  end
  resources :hr_staffs do
    collection do
      post :create_employee
    end
  end
  
  post 'create_employee', to: 'hr_staffs#create_employee'
end

app/models/hr_staff.rb
class HrStaff < ApplicationRecord
  mount_uploader :image, HrImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :employee_record, as: :employee
  # ======================================================================
  # This validation ensures that both first_name and last_name are present 
  # before saving the model.
  # ----------------------------------------------------------------------
  validates :first_name, :last_name, presence: true
  
  #TODO=> SETUP METHODS
  def full_name
    "#{first_name} #{last_name}"
  end

  # ========================
  # Updates employee records
  # ------------------------
  def update_employee_records
    # Your logic here
  end
end

app/controllers/hr_staffs/registrations_controller.rb
module HrStaffs
  class RegistrationsController < Devise::RegistrationsController
    before_action      :configure_permitted_parameters, if: :devise_controller?
    skip_before_action :authenticate_user, only: [:new, :create]

    protected
    # ==============================================================================
    # This method is used to specify the parameters that are permitted during
    # the sign-up process.
    # ------------------------------------------------------------------------------
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation, :image])
    end
  end
end

app/controllers/hr_staffs/sessions_controller.rb
# For HR Staffs
module HrStaffs
  class SessionsController < Devise::SessionsController
   
  end
end

app/controllers/hr_staffs_controller.rb
class HrStaffsController < ApplicationController

  # ==============================================================================
  # This method handles the index action for the HrStaffsController.
  # It sets up pagination, applies filters based on the role,
  # and calculates the total number of pages and records.
  # ------------------------------------------------------------------------------
  def index
    # Filtering
    @initial_letter = params[:initial_letter] || 'A'
    @role           = params[:role] || 'HrStaff'
    @date_range     = params[:date_range]

    maintenance_query = {}
    management_query  = {}
    hr_query          = {}

    # Pagination
    @page = params[:page].to_i
    @page = 1 if @page.zero?
    @number_of_entries_to_show = 10
    if @role.present?
      @per_page = @number_of_entries_to_show
    else
      @per_page = (@number_of_entries_to_show / 3.0).ceil
    end

    offset = (@page - 1) * @per_page

    if @role.present?
      case @role
      when "MaintenanceStaff"
        maintenance_query = MaintenanceStaff.all
        maintenance_query = maintenance_query.where("last_name LIKE ?", "#{@initial_letter}%")  if @initial_letter.present?
        maintenance_page  = maintenance_query.offset(offset).limit(@per_page).order(created_at: :desc)
      when "ManagementStaff"
        management_query  = ManagementStaff.all
        management_query  = management_query.where("last_name LIKE ?", "#{@initial_letter}%")   if @initial_letter.present?
        management_page   = management_query.offset(offset).limit(@per_page).order(created_at: :desc)
      when "HrStaff"
        hr_query = HrStaff.all
        hr_query = hr_query.where("last_name LIKE ?", "#{@initial_letter}%") if @initial_letter.present?
        hr_page = hr_query.offset(offset).limit(@per_page).order(created_at: :desc)
      end
    else
      # Base queries
      hr_query          = HrStaff.all
      maintenance_query = MaintenanceStaff.all
      management_query  = ManagementStaff.all

      maintenance_query = maintenance_query.where("last_name LIKE ?", "#{@initial_letter}%")  if @initial_letter.present?
      management_query  = management_query.where("last_name LIKE ?",  "#{@initial_letter}%")  if @initial_letter.present?
      hr_query          = hr_query.where("last_name LIKE ?",          "#{@initial_letter}%")  if @initial_letter.present?

      maintenance_page  = maintenance_query.offset(offset).limit(@per_page)
      management_page   = management_query.offset(offset).limit(@per_page)
      hr_page           = hr_query.offset(offset).limit(@per_page)
    end

    # Initialize @all_staffs
    @all_staffs = {
      hr_staffs:          hr_page,
      maintenance_staffs: maintenance_page,
      management_staffs:  management_page
    }

    # Set the total number of records based on your current filters
    @total_records       = hr_query.count + maintenance_query.count + management_query.count
    @grand_total_records = HrStaff.all.count + MaintenanceStaff.all.count + ManagementStaff.all.count

    # Calculate total pages for pagination
    @total_pages = (@total_records.to_f / @per_page).ceil
  end




  # =======================================================
  # Initialize a new Employee object for the form
  # -------------------------------------------------------
  def new
    @employee = params[:type].constantize.new if params[:type].in?(['HrStaff', 'MaintenanceStaff', 'ManagementStaff'])
    @employee ||= HrStaff.new
  end
  
  def create
    create_employee
  end
  
  # ============================================================================
  # Creates a new employee using the EmployeeFactory, assigns default login
  # credentials for the first time, and redirects or renders errors accordingly
  # ============================================================================
  def create_employee
    employee_type       = params[:hr_staff][:type]
    employee_attributes = params.require(:hr_staff).permit(:first_name, :last_name, :type)
    employee_attributes = employee_attributes.except(:type) # Remove :type
  
    begin
      # Create employee using EmployeeFactory
      new_employee = EmployeeFactory.create_employee(employee_type, employee_attributes)
      
      if new_employee.persisted?
        # Assign default login credentials
        default_password      = '12345678'
        new_employee.email    = "#{new_employee.first_name.downcase}.#{new_employee.last_name.downcase}@devry.edu"
        new_employee.password = default_password
  
        if new_employee.save
          redirect_to hr_staffs_path, notice: 'Employee was successfully created.'
        else
          flash.now[:alert] = new_employee.errors.full_messages.join(", ")
          render :new
        end
      else
        flash.now[:alert] = new_employee.errors.full_messages.join(", ")
        render :new
      end
    rescue => e
      flash.now[:alert] = e.message
      render :new
    end
  end
  
  def edit
     @hr_staff = HrStaff.find(params[:id])
  end
  
  def update
    @hr_staff = HrStaff.find(params[:id])
    if @hr_staff.update(hr_staff_params)
      if hr_staff?
        redirect_to "/", notice: 'HR Employee was successfully updated.'
      else
        redirect_to hr_staffs_path, notice: 'HR Employee was successfully updated.'
      end
    else
      flash.now[:alert] = @hr_staff.errors.full_messages.join(", ")
        respond_to do |format|
          format.turbo_stream { render turbo_stream: turbo_stream.replace('alert', 
                                                                          partial: 'turbo_layouts/alert', 
                                                                          locals: { alert: flash.now[:alert] }) }
          format.html { render :edit }
      end
    end
  end
  
  def show
    @hr_staff = HrStaff.find(params[:id])
  end
  
  def destroy
    @hr_staff = HrStaff.find(params[:id])
    @hr_staff.destroy
    current_letter = params[:current_letter]
    redirect_to hr_staffs_path(initial_letter: current_letter)
  end
  
  private
  def hr_staff_params
    params.require(:hr_staff).permit(:first_name, :last_name, :role, :image)
  end
  
  
  
  
  
  
  
  
  ##################################################################################
  ## DEVISE METHODS
  ################################################################################## 
  # # ==============================================================================
  # # This before_action ensures that only HR Staff can access specific actions
  # # ------------------------------------------------------------------------------
  # before_action :ensure_hr!, only: [:some_hr_action]
  #
  # private
  #
  # # ==============================================================================
  # # This method ensures the current user is HR Staff
  # # ------------------------------------------------------------------------------
  # def ensure_hr!
  #   unless current_staff.is_a? HrStaff
  #     redirect_to root_path, alert: 'Not authorized'
  #   end
  # end
  #
  
  
  
  
  
  
  
  
  
  
end

app/helpers/hr_staffs_helper.rb
module HrStaffsHelper
  include ConsoleColors
  def log(var, string)
    debug(var, string)
  end
end

app/views/hr_staffs/edit.html.slim
- title       =  hr_staff? ? "Edit Your Profile"   : "Edit HR Employee Profile"
- button_text =  hr_staff? ? "Update Your Profile" : "Update HR Employee"
- back_link   =  hr_staff? ? "/" : "/hr_staffs"

.container.col.no-pad
  #alert

.container.col
  h1.space-bot-xl #{title}
  i.fa-solid.fa-user-pen.space-bot-xl style="color: white; font-size: 7rem;"
  = form_with(model: @hr_staff, local: true, class: 'form-container') do |f|
    .form-group
      = f.label      :first_name, class: 'form-label'
      = f.text_field :first_name, class: 'form-input'
    
    .form-group
      = f.label      :last_name, class: 'form-label'
      = f.text_field :last_name, class: 'form-input'

    .form-group
      = f.label :image, 'Profile Image', class: 'form-label'
      = f.file_field :image, class: 'form-input'

    .form-actions
      /## UPDATE BUTTON ## 
      button.btn.btn-primary type="submit"
        i.fa-solid.fa-plus
        |  #{button_text}
  
  .navigation
    /## BACK BUTTON ##
    = link_to  back_link, class: "btn btn-secondary" do
      i.fa-solid.fa-chevron-left
      |  Back  

app/views/hr_staffs/index.html.slim
form#hiddenDeleteForm method="post" style="display:none;"
  input type="hidden" name="_method" value="delete"
  input type="hidden" name="authenticity_token" value="#{form_authenticity_token}"
  input type="hidden" id="currentLetter" name="current_letter" value=""
  input type="hidden" id="currentRole"   name="current_role" value=""

.container.col  style="padding-top: 5px"
  /## LETTER FILTER SECTION ##
  .letter-filter
    - ('A'..'Z').each do |letter|
      - active_class = (letter == @initial_letter) ? 'active-letter' : ''
      a.letter-link href="#" class="#{active_class}" data-letter=letter = letter

  /## ROLE FILTER SECTION ##
  .role-filter
    label for="role" Filter by role:
    | &nbsp
    select#role.form-control.modern-select
      option value="HrStaff"          selected=(@role == "HrStaff")          HR Staff
      option value="MaintenanceStaff" selected=(@role == "MaintenanceStaff") Maintenance Staff
      option value="ManagementStaff"  selected=(@role == "ManagementStaff")  Management Staff
    | &nbsp
    button#apply_filters.btn.btn-primary.modern-button Apply Filter
    = link_to "hr_staffs/new", class: 'add-button modern-button' do
      i.fa-solid.fa-user-plus
      |  Add Employee
  table.dark-table style="width: 1050px; padding: 0px;"
    thead
      tr
        th.sortable data-sort="first_name"  First Name
        th.sortable data-sort="last_name"   Last Name
        th.sortable data-sort="role"        Role
        th.sortable data-sort="created_at"  Employment Date
        th Actions
    tbody style=" padding: 0px;"
      - @all_staffs.each do |type, staffs|
        - if staffs.present?
          - staffs.each do |staff|
            tr.row.no-pad  data-first_name=staff.first_name data-last_name=staff.last_name data-role=staff.class.name data-created_at=staff.created_at.to_i
              td.no-pad  = staff.first_name
              td.no-pad  = staff.last_name
              td.no-pad  = staff.class.name
              td.no-pad  = staff.created_at.strftime("%d %b %Y")
              td.no-pad
                .container.no-pad
                  = link_to "#{type}/#{staff.id}", class: 'view-button' do
                    i.fa-regular.fa-id-card
                    |  View
                  = link_to "#{type}/#{staff.id}/edit", class: 'edit-button' do
                    i.fa-solid.fa-user-pen
                    |  Edit
                  /## DELETE BUTTON ##
                  a.open-modal.delete-button data-url=send("#{type.to_s.singularize}_path", staff)
                    i.fa-solid.fa-trash
                    |  Delete

  /## PAGINATION SECTION ##
  .pagination
    - prev_page     = [@page - 1, 1].max
    - next_page     = [@page + 1, @total_pages].min
    - prev_disabled = (@page == 1) ? 'disabled' : ''
    - next_disabled = (@page == @total_pages) ? 'disabled' : ''
    = link_to raw('<i class="fas fa-arrow-left"></i>'),
            url_for(request.query_parameters.merge(page: prev_page)),
            class: "pagination-button prev-button #{prev_disabled}",
            rel: ('nofollow' if @page == 1),
            data: { disabled: (@page == 1) }

    - window_size = 3 # Number of pages to show around the current page
    - start_page  = [@page - window_size, 1].max
    - end_page    = [@page + window_size, @total_pages].min


    - start_record = (@page - 1) * @per_page + 1
    - end_record = [@page * @per_page, @total_records].min

    - if start_page > 1
      = link_to '1', url_for(request.query_parameters.merge(page: 1)), class: 'pagination-button'

    - (start_page..end_page).each do |page_num|
      - active_class = (page_num == @page) ? 'active-page' : ''
      = link_to page_num, url_for(request.query_parameters.merge(page: page_num)), class: "pagination-button #{active_class}"

    - if end_page < @total_pages
      = link_to @total_pages, url_for(request.query_parameters.merge(page: @total_pages)), class: 'pagination-button'

    = link_to raw('<i class="fas fa-arrow-right"></i>'),
            url_for(request.query_parameters.merge(page: next_page)),
            class: "pagination-button next-button #{next_disabled}",
            rel: ('nofollow' if @page == @total_pages),
            data: { disabled: (@page == @total_pages) }

  /## PAGINATION METRICS ##
  - if @total_records > 0
    .pagination-metrics
      - start_record = (@page - 1) * @per_page + 1
      - end_record = [@page * @per_page, @total_records].min

      | Showing #{start_record} to #{end_record} of #{@total_records} records
      br
      | Total Staff: #{@grand_total_records}

  /## DASHBOARD BUTTON ##
  .space-bot-m
  = link_to '/', class: 'dashboard-button' do
    i.fa-solid.fa-house
    |  Back to Dashboard


  /###############################################################################
  /## MODAL SECTION ##
  /###################
  #deleteModal.modal
    .modal-content
      h4.space-bot-xl style="color: black; font-size: 1.2rem" Are you sure you want to delete this HR Employee?
      .modal-actions

        /## CONFIRM MODAL BUTTON ##
        = link_to '#', id: 'confirmDelete', class: 'delete-button' do
          i.fa-solid.fa-thumbs-up
          |  Yes, Delete

        /## CANCEL MODAL BUTTON ##
        a.btn.modal-close
          i.fa-solid.fa-thumbs-down
          |  No, Cancel

style
  |
    .no-pad { padding: 0px !important; }
    .letter-filter {margin-top: 0px}


javascript:
    $(document).ready(function () {
        $('.open-modal').on('click', function (e) {
            const deleteUrl = $(this).data('url');
            const currentLetter = $('.active-letter').data('letter'); // Get the current active letter
            $('#hiddenDeleteForm').attr('action', deleteUrl);
            $('#currentLetter').val(currentLetter); // Set the current letter
            $('#deleteModal').show();
        });

        $('#confirmDelete').on('click', function (e) {
            e.preventDefault();
            $('#hiddenDeleteForm').submit();

        });

        $('.modal-close').on('click', function () {
            $('#deleteModal').hide();
        });


        // When a letter is clicked
        $('.letter-link').click(function (e) {
            e.preventDefault();
            const letter = $(this).data('letter');
            updateFilters({initial_letter: letter, page: 1});
        });

        // When the role dropdown changes
        $('#role').change(function () {
            const role = $(this).val();
            updateFilters({role: role});
        });

        // When the "Apply Filter" button is clicked
        $('#apply_filters').click(function (e) {
            e.preventDefault();
            applyFilters();
        });

        function updateFilters(newParams) {
            const params = new URLSearchParams(window.location.search);
            Object.keys(newParams).forEach(key => {
                const value = newParams[key];
                if (value) {
                    params.set(key, value);
                } else {
                    params.delete(key);
                }
            });
            window.location.search = params.toString();
        }

        function applyFilters() {
            // Collect all filter values and update the URL
            const role = $('#role').val();
            updateFilters({role: role});
        }
    });

app/views/hr_staffs/new.html.slim
.container.col.no-pad
  #alert

.container.col
  h1.space-bot-xl Add Employee
  i.fa-solid.fa-user-plus.space-bot-xl style="font-size: 7rem;"
  = form_with(model: @employee, url: create_employee_path, local: true, class: 'form-container') do |f|
    = f.hidden_field :type, id: 'employee_type_hidden'
    .form-group
      = label_tag :employee_type, 'Employee Role', class: 'form-label'
      br
      = select_tag :employee_type, 
              options_for_select([['Select Type', ''],
                                  ['Human Resources', 'HrStaff'], 
                                  ['Maintenance', 'MaintenanceStaff'], 
                                  ['Management', 'ManagementStaff']]), 
                                  class: 'form-input', 
                                  id:    'employee_type_select'
    .form-group
      = f.label      :first_name, class: 'form-label'
      = f.text_field :first_name, class: 'form-input'
    .form-group
      = f.label      :last_name,  class: 'form-label'
      = f.text_field :last_name,  class: 'form-input'
    .form-actions
      button.btn.btn-primary type="submit"
        i.fa-solid.fa-plus
        |  Add Employee

  .navigation
    /## BACK BUTTON ##
    = link_to '/hr_staffs', class: "btn btn-secondary" do
      i.fa-solid.fa-chevron-left
      |  Back
      
  .space-bot-xl
  .demonstration     
    | Login credentials for newly created employees are:
    br
    | Email: first_name.last_name@devry.edu (ex. john.doe@devry.edu)
    br
    | Password: 12345678
    
javascript:
  $(document).ready(function() {
    $('#employee_type_select').change(function() {
      $('#employee_type_hidden').val($(this).val());
    });
  });


style
  | 
    #employee_type_select {
      background-color:#333; 
      border-radius: 5px; 
      color: white; 
      width: 245px;
      height: 40px; 
    }
    .demonstration {
      color: grey; 
      font-size: .8rem; 
      width: 500px; 
    }
    .align-left { text-align: left}

app/views/hr_staffs/show.html.slim
- staff = @hr_staff
.container.col.no-pad
  h1.space-bot-m HR Staff Details
  
  /## ICON ##
  - if staff.image.present?
    = image_tag staff.image.url, alt: "#{staff.first_name}", class: 'profile-image space-bot-m'
  - else
    i.fa-regular.fa-id-card.fa-2xl.space-bot-xxl style="color: white; font-size: 7rem; margin-top: 80px"
  
  div.fake-table
    div.fake-table-row.fake-table-header
      div.fake-table-cell First Name
      div.fake-table-cell Last Name
      
    div.fake-table-row.fake-table-body
      div.fake-table-cell = staff.first_name
      div.fake-table-cell = staff.last_name
  br
  .container.no-pad
    /## EDIT BUTTON ##
    = link_to "/hr_staffs/#{staff.id}/edit", class: 'btn' do
      i.fa-solid.fa-user-pen
      |  Edit

    /## BACK BUTTON ##
    = link_to '/hr_staffs', class: "btn" do
      i.fa-solid.fa-chevron-left
      |  Back

style
  |
    .profile-image {height: 300px; border-radius: 8px}