config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  ##############################################################################
  ## ROOT LOCATION ##
  ###################
  root "dashboard#index"
  
  ##############################################################################
  ## DEVISE ROUTES ##
  ###################
  devise_for :hr_staffs,          path: 'hr_staffs',          controllers: { sessions: 'hr_staffs/sessions', registrations: 'hr_staffs/registrations' }
  devise_for :maintenance_staffs, path: 'maintenance_staffs', controllers: { sessions: 'maintenance_staffs/sessions' }
  devise_for :management_staffs,  path: 'management_staffs',  controllers: { sessions: 'management_staffs/sessions' }
  
  get 'new_user_session' => 'sessions#new', as: :new_user_session
  
  ##############################################################################
  ## MAIN ROUTES ##
  #################
  resources :maintenance_staffs
  resources :management_staffs
  resources :employee_records
  resources :reports
  
  ##############################################################################
  ## Custom ROUTES ##
  ###################
  resources :equipment_inventories do
    member do
      post :toggle_status
    end
  end
  resources :hr_staffs do
    collection do
      post :create_employee
    end
  end
  
  post 'create_employee', to: 'hr_staffs#create_employee'
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :management_staff, foreign_key: 'management_staffs_id'
  validates :start_date, presence: true
  validates :end_date, presence: true

  
  def checked_out?
    check_in_status == 1
  end
  def checked_in?
    check_in_status == 0
  end
  def removed?
    check_in_status == -1
  end
  def created?
    check_in_status == 0
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include ConsoleColors
  
  def index
    @reports = Report.order(id: :desc).limit(100)
  end

  def generate
    @report = Report.find(params[:id])
    @report.generate
  end
  
  def new
    @report = Report.new
  end
  
  # =========================================================================
  # handles the creation of a new report. It initializes a new report
  # object, sets its attributes, and then attempts to save it to the database
  # -------------------------------------------------------------------------
  def create
    @report = Report.new(report_params)
    @report.management_staffs_id = current_management_staff.id if management?
    
    # Set check_in_status based on report_type
    case @report.report_type
    when 'Checked In'
      @report.check_in_status = 0  
    when 'Checked Out'
      @report.check_in_status = 1  
    when 'All'
      @report.check_in_status = nil
    when 'Removed'
      @report.check_in_status = -1  
    end
    
    if @report.save
      # Handle successful save, for example, redirect to the report show page
      redirect_to @report
    else
      # Handle unsuccessful save, for example, render the new template again
      debug(@report.errors.full_messages, "Validation Errors")
      render 'new'
    end
  end
  
  # ============================================================================
  # The show action fetches a report based on its ID and then queries the
  # EquipmentInventory based on the report's parameters. If a parameter is nil,
  # it is ignored in the query.
  # ----------------------------------------------------------------------------
  def show
    @report = Report.find(params[:id])
    debug(@report, "report")
    @queried_equipment = EquipmentInventory.all
    @equipment_history = EquipmentMovement.all
    
    if @report.maintenance_staffs_id.present?
      @maintenance_staff = MaintenanceStaff.find(@report.maintenance_staffs_id)
      @queried_equipment = @queried_equipment.where(maintenance_staffs_id: @maintenance_staff.id)
    end
  
    if @report.check_in_status.present?
      if @report.check_in_status == -1
        @queried_equipment = @queried_equipment.where(deleted: true)
      else
        @queried_equipment = @queried_equipment.where(status: @report.check_in_status) 
      end
    end
    
    if @report.start_date.present? && @report.end_date.present?
      start_date  = @report.start_date
      end_date    = @report.end_date
      date_column = @report.check_in_status == 0 ? 'last_checked_in_at' : 'last_checked_out_at'
      @queried_equipment = @queried_equipment.where("#{date_column} BETWEEN ? AND ?", start_date, end_date)
    end
    
    equipment_inventory_ids = @queried_equipment.pluck(:id)
    @equipment_history = EquipmentMovement
                           .where(equipment_inventory_id: equipment_inventory_ids)
                           .order(moved_at: :desc)
    @queried_equipment = @queried_equipment.order(created_at: :desc)
    debug(@queried_equipment, "@queried_equipment")
  end
  
  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    redirect_to reports_path, notice: 'Report was successfully removed.'
  end

  private
  # ==================================================================
  # Defines the permitted parameters for creating or updating a report
  # ------------------------------------------------------------------
  def report_params
    params.require(:report).permit(:report_type, 
                                          :maintenance_staffs_id,
                                          :check_in_status, 
                                          :start_date, 
                                          :end_date,
                                          :authenticity_token)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_equipment_report.html.slim
tr
  td = equipment.id
  td = equipment.equipment_name
  td = equipment.serial
  td = equipment.created_at.strftime("%d %b %Y")
  td
    i.fa class=(equipment.checked_in? ? "fa-check-circle report-green" : "fa-exclamation-circle") aria-hidden="true"
      - if equipment.checked_in?
        |  Checked In
      - else
        |  Checked Out
  td
    - if equipment.image.present?
      = image_tag equipment.image.url(:thumb), alt: "#{equipment.equipment_name} Thumbnail", class: 'equipment-thumbnail'
    - else
      | No Image
      | &nbsp
      i.fa-solid.fa-image
style
  |
    .equipment-container {  display: flex; 
                            flex-direction: column; 
                            justify-content: center;
                            align-items: center;
                          }
    .shrink-h {height: 40px; padding: 0px; text-align: center }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
      font-size: 16px;
    }

    th, td {
      padding: 2px;
      border: 1px solid #ddd;
      text-align: center;
    }

    th {
      background-color: #423f3f;
      color: white;
    }

    td {
      background-color: #3e3c3c;
    }

    .equipment-thumbnail {
      max-width: 100px;
      height: auto;
    }

    .equipment-container {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }

    .shrink-h {
      height: 40px;
      padding: 0px;
      text-align: center;
    }
    .report-green {color: #0dff00}

app/views/reports/_history_report.html.slim
- equipment = EquipmentInventory.find(record.equipment_inventory_id)
- staff = {}
- staff = MaintenanceStaff.find(record.maintenance_staff_id) if record.maintenance_staff_id.present?

tr
  td= equipment.id
  td= equipment.equipment_name
  td= equipment.serial
  td
    - if staff.present?
     | #{staff.first_name} #{staff.last_name}
    - else
      | Employee Removed
  td= record.action
  td= record.moved_at.strftime("%d %b %Y %H:%M")
  

style
  |
    .equipment-container {  display: flex; 
                            flex-direction: column; 
                            justify-content: center;
                            align-items: center;
                            
                          }
    .shrink-h {height: 40px; padding: 0px; text-align: center }

app/views/reports/index.html.slim
form#hiddenDeleteForm method="post" style="display:none;"
  input type="hidden" name="_method" value="delete"
  input type="hidden" name="authenticity_token" value="#{form_authenticity_token}"

.container.col
  h1.space-bot-xl Reports
  i.fa-solid.fa-file-lines.space-bot-xl style="font-size: 7rem;"
  = link_to "reports/new", class: 'add-button' do
    i.fa-solid.fa-file-circle-plus
    |  Generate Report
  .space-bot-s
  table.dark-table 
    thead
      tr
        th Report ID
        th Report Type
        th Staff ID
        th Generated By
        th Date Created
        th Action
    tbody
      - @reports.each do |report|
        - staff = {}
        - if report.management_staffs_id?
          - staff = ManagementStaff.find(report.management_staffs_id)
        - staff_name = report.management_staffs_id? ? staff.full_name : "Employee Removed"

        tr
          td= report.id
          td= report.report_type
          td= report.management_staffs_id
          td style="text-align: left"
            - if staff.image.present?
              = image_tag staff.image.url(:thumb), alt: "#{staff.first_name} Thumbnail", class: 'profile-image'
            - else
              i.fa-regular.fa-user.fa style=" font-size: 1.2rem;"
            | &nbsp
            =staff_name
          td= report.created_at.strftime("%d %b %Y")
          td
            = link_to "View", report_path(report), class: 'view-button'
            = link_to "Delete", report_path(report), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-button'

  /## DASHBOARD BUTTON ##
  .space-bot-m
  = link_to '/', class: 'dashboard-button' do
    i.fa-solid.fa-house
    |  Back to Dashboard

/## MODAL SECTION ##
#deleteModal.modal
  .modal-content
    h4.space-bot-xl style="color: black; font-size: 1.2rem" Are you sure you want to delete this Record?
    .modal-actions
      = link_to '#', id: 'confirmDelete', class: 'delete-button' do
        i.fa-solid.fa-thumbs-up
        |  Yes, Delete
      a.btn.modal-close
        i.fa-solid.fa-thumbs-down
        |  No, Cancel

style
  |
    .dark-table {
      width: 1000px; /* or any specific width */
    }


/###############################################################################
/## JAVASCRIPT SECTION ##
/########################
javascript:
    $(document).ready(function () {
        // Use event delegation for dynamically added rows
        $('tbody').on('click', '.open-modal', function (e) {
            e.preventDefault();
            const deleteUrl = $(this).data('url');
            $('#hiddenDeleteForm').attr('action', deleteUrl);
            $('#deleteModal').show();
        });
        $('#confirmDelete').on('click', function (e) {
            e.preventDefault();
            $('#hiddenDeleteForm').submit();
        });

        $('.modal-close').on('click', function () {
            $('#deleteModal').hide();
        });
    });

app/views/reports/new.html.slim
.container.col.no-pad
  #alert

.container.col
  h1.space-bot-xl Generate Report
  i.fa-solid.fa-file-lines.space-bot-xl style="font-size: 7rem;"
    / = form_with(url: reports_path, method: :post, local: true, class: 'form-container', id: 'report_form') do |f|
  = form_with(model: @report, local: true, class: 'form-container', id: 'report_form') do |f|
    .form-group
      = f.label  :report_type, class: 'form-label'
      = f.select :report_type, 
              ['Checked In', 
               'Checked Out', 
               'All', 
               'Removed'], 
              {}, 
              { id: 'report_type', 
                class: 'form-input' }
      
      
      
  
    .form-group
      = f.label      :start_date, 'Start Date', class: 'form-label'
      = f.date_field :start_date, id: 'start_date', class: 'form-input'
  
    .form-group
      = f.label      :end_date, 'End Date', class: 'form-label'
      = f.date_field :end_date, id: 'end_date', class: 'form-input'
        
    .form-group
      = f.label             :maintenance_staffs_id, 'Maintenance Staff', class: 'form-label'
      = f.collection_select :maintenance_staffs_id, 
                             MaintenanceStaff.all, 
                             :id, 
                             :full_name, 
                             { include_blank: 'All' }, 
                             class: 'form-input'

    .form-actions
      button.btn.btn-primary type="submit"
        i.fa-solid.fa-plus
        |  Generate Report

  .navigation
    = link_to '/reports', class: "btn btn-secondary" do
      i.fa-solid.fa-chevron-left
      |  Back

app/views/reports/show.html.slim
#loadingSpinner
  = image_tag 'spinner.gif', alt: 'Loading...'
#mainContent style="display: none"
  - report = @report
  .container.col
    h1 Report Details
    i.fa-solid.fa-file-lines.space-bot-xl style="font-size: 7rem"

    div.fake-table
      div.fake-table-row.fake-table-header
        div.fake-table-cell Generated Report Details

      div.fake-table-row.fake-table-body
        div.fake-table-cell Report ID
        div.fake-table-cell = report.id

      div.fake-table-row.fake-table-body
        div.fake-table-cell Report Type
        div.fake-table-cell = report.report_type

      div.fake-table-row.fake-table-body
        div.fake-table-cell Date Generated
        div.fake-table-cell = report.created_at.strftime("%d %b %Y")

      div.fake-table-row.fake-table-body
        div.fake-table-cell Generated By
        div.fake-table-cell = ManagementStaff.find(report.management_staffs_id).full_name

  -if @maintenance_staff.present?
    h1.center Equipment Report For Maintenance Employee #{@maintenance_staff.full_name}
  - else
    h1.center Report for #{@report.report_type} Equipment
  -if @queried_equipment.present?
    table
      thead
        th ID
        th Item
        th Serial
        th Added
        th status
        th Image
      - @queried_equipment.each do |equipment|
        = render partial: 'equipment_report',  locals: {equipment: equipment}

    .space-bot-xxl
    h1.center History Log
    .container.col.no-pad
      table.table-modern
        thead
          th ID
          th Item
          th Serial
          th Employee
          th Action
          th Date
        - @equipment_history.each do |record|
          = render partial: 'history_report', locals: { record: record }

  - else
    h1.center.yellow No Available Data

  .container
    /## BACK BUTTON ##
    = link_to '/reports', class: "btn" do
      i.fa-solid.fa-chevron-left
      |  Back
  
style
  |
    .center {text-align: center} 
    .yellow {color: yellow} 
    .pad {padding: 10px}

javascript:
    $(document).ready(function () {
        console.log("Document is ready");
        $('#loadingSpinner').hide();
        $('#mainContent').show();
    });