config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  ##############################################################################
  ## ROOT LOCATION ##
  ###################
  root "dashboard#index"
  
  ##############################################################################
  ## DEVISE ROUTES ##
  ###################
  devise_for :hr_staffs,          path: 'hr_staffs',          controllers: { sessions: 'hr_staffs/sessions', registrations: 'hr_staffs/registrations' }
  devise_for :maintenance_staffs, path: 'maintenance_staffs', controllers: { sessions: 'maintenance_staffs/sessions' }
  devise_for :management_staffs,  path: 'management_staffs',  controllers: { sessions: 'management_staffs/sessions' }
  
  get 'new_user_session' => 'sessions#new', as: :new_user_session
  
  ##############################################################################
  ## MAIN ROUTES ##
  #################
  resources :maintenance_staffs
  resources :management_staffs
  resources :employee_records
  resources :reports
  
  ##############################################################################
  ## Custom ROUTES ##
  ###################
  resources :equipment_inventories do
    member do
      post :toggle_status
    end
  end
  resources :hr_staffs do
    collection do
      post :create_employee
    end
  end
  
  post 'create_employee', to: 'hr_staffs#create_employee'
end

app/views/layouts/_footer.html.slim
/ ==============================================================================
/ This adds a sticky footer at the bottom of the screen with the copyright notice.
/ ------------------------------------------------------------------------------
style
  |
    footer {
      background-color: #222;
      padding: .5em;
      text-align: center;
      font-size: 1.1em;
      position: sticky;
      bottom: 0;
      z-index: 1000;
      width: 100%;
    }
    footer p {
      color: white;
      margin: 0;
      padding: 0.2em 0;
    }
    footer .tech-stack {
      font-size: 0.9em;
      margin-top: 0.5em;
    }

footer
  p 
    | © 2023 Equipment Checkout System (ECS)
  p.tech-stack
    | Developed with
    | &nbsp
    span class="mdi mdi-language-ruby"
    | &nbsp
    | Ruby,
    | &nbsp
    span class="mdi mdi-language-ruby-on-rails"
    | &nbsp
    | Ruby on Rails,
    | &nbsp
    span class="mdi mdi-language-javascript"
    | &nbsp
    | Javascript,
    | &nbsp
    span class="mdi mdi-jquery"
    | &nbsp
    |jQuery,
    | &nbsp
    span class="mdi mdi-database-search"
    | &nbsp
    | PostgreSQL,
    | &nbsp
    span class="mdi mdi-aws"
    | &nbsp
    | AWS S3,
    | &nbsp
    span class="mdi mdi-language-css3"
    | &nbsp
    | CSS,
    | &nbsp
    | and
    | &nbsp
    span class="mdi mdi-language-html5"
    | Slim

app/views/layouts/_header.html.slim
/ ================================================================================
/ This adds navigation links. The header will also stick to the top of the screen.
/ --------------------------------------------------------------------------------
style
  |
    header {
      background-color: #222;
      padding: .5em;
      padding-bottom: 0px;
      text-align: center;
      font-size: 1.2em;
      position: sticky;
      top: 0;
      z-index: 1000;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    header_two {
      background-color: #1a1a1a;
      padding: 0px;
      border-radius: 0px 0px 10px 10px;
      position: sticky;
      top: 60px;
      z-index: 9999;
    }
    header_two>h2 {
      font-size: 1.2rem;
      padding: 0px;
      margin-top: 0px

    }
    nav {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 1em;
      position: relative;
    }
    nav a, .nav-button {
      color: white;
      text-decoration: none;
      padding: 0.5em 1em;
      border-radius: 4px;
      transition: background-color 0.3s ease;
      display: flex;
      align-items: center;
      gap: 0.5em;
    }
    nav a:hover, .nav-button:hover {
      background-color: #555;
    }
    nav i, .nav-button i {
      font-size: 1.2em;
    }
    .nav-button {
      background-color: #222;
      border: none;
      cursor: pointer;
      font-size: 1rem;
    }
    .logout-button {
      margin-left: auto;

    }

- if current_staff.present?
  - logout_path = Rails.application.routes.url_helpers.send("destroy_#{current_staff.class.name.underscore}_session_path")
  - role = ""
  - icon = ""
  - edit_path = ""

  - if hr_staff?
    - role = "Human Resources Employee Roster"
    - icon = "fa-people-group"
    - edit_path = edit_hr_staff_path(current_staff)
  - elsif maintenance?
    - role = "Maintenance Equipment Inventory"
    - icon = "fa-toolbox"
    - edit_path = edit_maintenance_staff_path(current_staff)
  - elsif management?
    - role = "Management Reports"
    - icon = "fa-file-alt"
    - edit_path = edit_management_staff_path(current_staff)

  header style="display: flex; justify-content: space-between; align-items: center; gap: 220px; padding-top: 0px;  padding-bottom: 10px;"
    h2 style="font-size: 1.4rem; padding-top: 15px; padding-bottom: 0px; margin: 0px"
      | &nbsp
      i.fa-solid.fa-screwdriver-wrench
      | &nbsp
      | Equipment Checkout System (ECS)

    .div style="display: flex; gap: 5px; align-items: center"
      nav.space-top-s
        = button_to logout_path, method: :delete, class: 'nav-button logout-button', data: { turbolinks: false } do
          i.fa.fa-sign-out-alt
          | Logout

      = link_to edit_path do
        - if current_staff.image.present?
          = image_tag current_staff.image.url(:thumb), alt: "#{current_staff.first_name} Thumbnail", class: 'avatar-image'
        - else
          i.fa-solid.fa-user style="padding-top: 8px; color: white"

  header_two style="display: flex; justify-content: center; align-items: center; "
    h2 style="margin: 0px"
      = role
      | &nbsp
      i class=" fa-solid #{icon}"


- else
  header style="display: flex; justify-content: center;"
    h2 style=("font-size: 1.1rem; padding-bottom: 10px; padding-top: 10px margin: 0px;")
      | Welcome

.space-bot-m

style
  |
    .avatar-image {margin-top: 10px; border-radius: 50px; width: 70% }

app/views/layouts/application.html.slim
doctype html
html
  head
    title EquipmentCheckoutSystem
    meta name="viewport" content="width=device-width,initial-scale=1"

    script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/@mdi/font@7.3.67/scripts/verify.min.js"

    link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.3.0/css/all.css"
    link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@7.3.67/css/materialdesignicons.min.css"

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track" => "reload"
    = stylesheet_link_tag "dark-mode" 
    = javascript_importmap_tags

  body.dark-mode
    = render "/layouts/header"
    main#content
      = yield
    = render "/layouts/footer"
    

style
  |
    body {
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    main#content {
      flex: 1;
    }

    footer {
      background-color: #222;
      padding: .5em;
      text-align: center;
      font-size: 1.1em;
      width: 100%;
    }

    footer p {
      color: white;
      margin: 0;
      padding: 0.2em 0;
    }

    footer .tech-stack {
      font-size: 0.9em;
      margin-top: 0.5em;
    }    